
INSERT INTO address (address_name) VALUES ('123 Main Street');
INSERT INTO address (address_name) VALUES ('456 Oak Avenue');
INSERT INTO address (address_name) VALUES ('789 Pine Lane');
INSERT INTO address (address_name) VALUES ('234 Elm Street');
INSERT INTO address (address_name) VALUES ('567 Maple Drive');
INSERT INTO address (address_name) VALUES ('890 Cedar Road');
INSERT INTO address (address_name) VALUES ('111 Birch Lane');
INSERT INTO address (address_name) VALUES ('222 Pine Street');
INSERT INTO address (address_name) VALUES ('333 Oak Lane');
INSERT INTO address (address_name) VALUES ('444 Maple Road');
INSERT INTO address (address_name) VALUES ('555 Cedar Avenue');
INSERT INTO address (address_name) VALUES ('666 Elm Drive');
INSERT INTO address (address_name) VALUES ('777 Birch Road');
INSERT INTO address (address_name) VALUES ('888 Pine Drive');
INSERT INTO address (address_name) VALUES ('999 Cedar Street');
INSERT INTO address (address_name) VALUES ('101 Oak Avenue');
INSERT INTO address (address_name) VALUES ('202 Maple Lane');
INSERT INTO address (address_name) VALUES ('303 Elm Road');
INSERT INTO address (address_name) VALUES ('404 Birch Drive');
INSERT INTO address (address_name) VALUES ('505 Pine Road');

INSERT INTO customer (name, last_name, email, age, address) VALUES ('John', 'Doe', 'john.doe@email.com', 25, 1);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Alice', 'Smith', 'alice.smith@email.com', 30, 2);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Bob', 'Johnson', 'bob.johnson@email.com', 22, 3);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Eva', 'Williams', 'eva.williams@email.com', 28, 4);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Charlie', 'Brown', 'charlie.brown@email.com', 35, 5);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Grace', 'Davis', 'grace.davis@email.com', 27, 6);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Daniel', 'Miller', 'daniel.miller@email.com', 29, 7);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Sophia', 'Moore', 'sophia.moore@email.com', 31, 8);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Oliver', 'White', 'oliver.white@email.com', 26, 9);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Mia', 'Hall', 'mia.hall@email.com', 33, 10);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Liam', 'Walker', 'liam.walker@email.com', 24, 11);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Emma', 'Baker', 'emma.baker@email.com', 32, 12);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Noah', 'Taylor', 'noah.taylor@email.com', 28, 13);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Ava', 'Hill', 'ava.hill@email.com', 36, 14);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Lucas', 'Clark', 'lucas.clark@email.com', 30, 15);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Isabella', 'Wright', 'isabella.wright@email.com', 29, 16);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Sophie', 'Johnson', 'sophie.johnson@email.com', 23, 17);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Jackson', 'Martin', 'jackson.martin@email.com', 26, 18);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Scarlett', 'Thompson', 'scarlett.thompson@email.com', 28, 19);
INSERT INTO customer (name, last_name, email, age, address) VALUES ('Aiden', 'Harris', 'aiden.harris@email.com', 31, 20);



INSERT INTO book (name, isbn, image) VALUES ('The Catcher in the Rye', '978-0-316-76948-0', 'catcher.jpg');
INSERT INTO book (name, isbn, image) VALUES ('To Kill a Mockingbird', '978-0-06-112008-4', 'mockingbird.jpg');
INSERT INTO book (name, isbn, image) VALUES ('1984', '978-0-452-28423-4', '1984.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Great Gatsby', '978-0-7432-7356-5', 'gatsby.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Pride and Prejudice', '978-0-19-953556-9', 'pride.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Moby-Dick', '978-1-85326-128-3', 'moby-dick.jpg');
INSERT INTO book (name, isbn, image) VALUES ('War and Peace', '978-0-670-53257-5', 'war-peace.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Hobbit', '978-0-261-10295-2', 'hobbit.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Frankenstein', '978-0-486-28223-0', 'frankenstein.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Lord of the Rings', '978-0-345-24011-7', 'lotr.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Odyssey', '978-0-19-953678-8', 'odyssey.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Brothers Karamazov', '978-0-14-044924-2', 'karamazov.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Alice in Wonderland', '978-1-60322-451-7', 'alice.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Shining', '978-0-385-12167-5', 'shining.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Don Quixote', '978-0-06-093434-7', 'don-quixote.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Hamlet', '978-0-7434-8485-5', 'hamlet.jpg');
INSERT INTO book (name, isbn, image) VALUES ('One Hundred Years of Solitude', '978-0-06-112008-4', 'solitude.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Picture of Dorian Gray', '978-1-85326-128-3', 'dorian-gray.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Dracula', '978-0-14-043701-9', 'dracula.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Canterbury Tales', '978-0-14-042234-4', 'canterbury.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Crime and Punishment', '978-0-553-21291-6', 'crime-punishment.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Grapes of Wrath', '978-0-14-303943-3', 'grapes-wrath.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Wuthering Heights', '978-0-14-143955-6', 'wuthering-heights.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Count of Monte Cristo', '978-1-85326-195-5', 'monte-cristo.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Iliad', '978-0-19-953679-5', 'iliad.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Great Expectations', '978-0-14-143956-3', 'great-expectations.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Scarlet Letter', '978-0-14-243726-1', 'scarlet-letter.jpg');
INSERT INTO book (name, isbn, image) VALUES ('A Tale of Two Cities', '978-0-14-143960-0', 'tale-two-cities.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Les Misérables', '978-0-14-044430-8', 'les-miserables.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Hound of the Baskervilles', '978-0-19-953686-3', 'hound-baskervilles.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Divine Comedy', '978-0-19-953564-4', 'divine-comedy.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Jungle Book', '978-0-14-062063-6', 'jungle-book.jpg');
INSERT INTO book (name, isbn, image) VALUES ('Anna Karenina', '978-0-19-953608-5', 'anna-karenina.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Call of the Wild', '978-0-14-243726-1', 'call-wild.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Wind in the Willows', '978-0-14-062063-6', 'wind-willows.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The Adventures of Sherlock Holmes', '978-0-19-953698-6', 'sherlock-holmes.jpg');
INSERT INTO book (name, isbn, image) VALUES ('The War of the Worlds', '978-0-553-21291-6', 'war-worlds.jpg');

